services:
  mongo:
    container_name: mongo-container
    image: mongo:8
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27018:27017"
  api:
    container_name: api-container
    build: .
    image: clean-arch
    restart: always
    command: npm run debug
    volumes:
      - ./dist/:/usr/repos/clean-arch/dist/
      - ./package.json:/usr/repos/clean-arch/package.json
    ports:
      - "8080:8080"
      - "8081:8081"
    links:
      - mongo
